use anyhow::{Context, Result};
use litkg_core::{emit_markdown, write_materialized_doc, MaterializedDoc, ParsedPaper, RepoConfig};
use std::fs;
use std::path::PathBuf;

pub struct GraphifySink;

impl GraphifySink {
    pub fn materialize(config: &RepoConfig, papers: &[ParsedPaper]) -> Result<Vec<PathBuf>> {
        fs::create_dir_all(&config.generated_docs_root).with_context(|| {
            format!("Failed to create {}", config.generated_docs_root.display())
        })?;
        let mut written = Vec::new();
        for paper in papers {
            let doc = emit_markdown(config, paper);
            write_materialized_doc(&doc)?;
            written.push(doc.path);
        }
        let index = build_index(config, papers);
        write_materialized_doc(&index)?;
        written.push(index.path);
        let manifest = build_manifest(config, &written)?;
        written.push(manifest);
        Ok(written)
    }
}

fn build_index(config: &RepoConfig, papers: &[ParsedPaper]) -> MaterializedDoc {
    let path = config.generated_docs_root.join("index.md");
    let mut lines = vec![
        "# Literature Index".to_string(),
        String::new(),
        "Generated by litkg-rs for graph-oriented literature ingestion.".to_string(),
        String::new(),
    ];
    for paper in papers {
        lines.push(format!(
            "- [{}]({}.md)",
            paper.metadata.title, paper.metadata.paper_id
        ));
    }
    MaterializedDoc {
        path,
        content: lines.join("\n"),
    }
}

fn build_manifest(config: &RepoConfig, written_docs: &[PathBuf]) -> Result<PathBuf> {
    let path = config.generated_docs_root.join("graphify-manifest.json");
    let payload = serde_json::json!({
        "generated_docs_root": config.generated_docs_root,
        "docs": written_docs,
        "graphify_rebuild_command": config.graphify_rebuild_command,
    });
    fs::write(&path, serde_json::to_string_pretty(&payload)?)
        .with_context(|| format!("Failed to write {}", path.display()))?;
    Ok(path)
}

#[cfg(test)]
mod tests {
    use super::*;
    use litkg_core::{DownloadMode, PaperSourceRecord, ParseStatus, SinkMode, SourceKind};

    #[test]
    fn writes_graphify_docs() {
        let dir = tempfile::tempdir().unwrap();
        let config = RepoConfig {
            manifest_path: dir.path().join("sources.jsonl"),
            bib_path: dir.path().join("references.bib"),
            tex_root: dir.path().join("tex"),
            pdf_root: dir.path().join("pdf"),
            generated_docs_root: dir.path().join("generated"),
            registry_path: None,
            parsed_root: None,
            neo4j_export_root: None,
            memory_state_root: None,
            sink: SinkMode::Graphify,
            graphify_rebuild_command: None,
            download_pdfs: false,
            relevance_tags: vec!["ViSTA-SLAM".into()],
            semantic_scholar: None,
        };
        let papers = vec![ParsedPaper {
            metadata: PaperSourceRecord {
                paper_id: "vista".into(),
                citation_key: Some("zhang2026vistaslam".into()),
                title: "ViSTA-SLAM".into(),
                authors: vec![],
                year: Some("2026".into()),
                arxiv_id: Some("2509.01584".into()),
                doi: None,
                url: None,
                tex_dir: None,
                pdf_file: None,
                source_kind: SourceKind::Bib,
                download_mode: DownloadMode::MetadataOnly,
                has_local_tex: false,
                has_local_pdf: false,
                parse_status: ParseStatus::MetadataOnly,
                semantic_scholar: None,
            },
            abstract_text: Some("Abs".into()),
            sections: vec![],
            figures: vec![],
            tables: vec![],
            citations: vec![],
            citation_references: Vec::new(),
            provenance: vec![],
        }];

        let written = GraphifySink::materialize(&config, &papers).unwrap();
        assert_eq!(written.len(), 3);
        assert!(config.generated_docs_root.join("vista.md").is_file());
        assert!(config.generated_docs_root.join("index.md").is_file());
        assert!(config
            .generated_docs_root
            .join("graphify-manifest.json")
            .is_file());
    }
}
