use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum NodeKind {
    Paper,
    BibEntry,
    Document,
    DocSection,
    CitationMention,
    Concept,
    AgentInstructionFile,
    AgentSkill,
    SkillTrigger,
    SkillScript,
    AgentBacklogIssue,
    AgentBacklogTodo,
    McpServer,
    McpTool,
    McpResource,
    McpPrompt,
    ContextPack,
    ContextLeaf,
    ExternalDocLeaf,
    Decision,
    OpenQuestion,
    ActionItem,
    CodeFile,
    CodeSymbol,
    Transcript,
    TranscriptTurn,
    Context7Leaf,
    Conflict,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EdgeKind {
    Cites,
    Mentions,
    Handles,
    UsesTool,
    ReadsResource,
    ResolvesTo,
    CanonicalizesTo,
    Aliases,
    Defines,
    Documents,
    Implements,
    Explains,
    Supports,
    Contradicts,
    Supersedes,
    DependsOn,
    HasTodo,
    RoutesTo,
    Includes,
    RequiresExternalProvider,
    SourceSpan,
    RequiresExternalDocs,
    HasEvidence,
}
